# 
name: tornado-weather
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip:
    - pandas=1.3.4
    - numpy=1.21.3
    - matplotlib=3.4.3
    - seaborn=0.11.2
    - scikit-learn=1.0.2
    - jupyterlab=3.2.1
    - ipykernel=6.4.1